name: getx_socket_io
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  #state management
  get: 4.6.5
  flutter: 
    sdk: flutter
    
  intl: ^0.17.0
  
  #network
  dio: ^4.0.6
  socket_io_client: ^2.0.0-beta.4-nullsafety.0


dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
